version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: place-postgres
    environment:
      POSTGRES_DB: place_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - place-network

  redis:
    image: redis:7-alpine
    container_name: place-redis
    ports:
      - "6379:6379"
    networks:
      - place-network

  mercure:
    image: dunglas/mercure
    container_name: place-mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_JWT_SECRET}'
      MERCURE_SUBSCRIBER_JWT_KEY: '${MERCURE_JWT_SECRET}'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:5173 https://localhost:5173 http://localhost:8000 https://localhost:8000 http://localhost:3001 https://localhost:3001
        anonymous
        subscriptions
    ports:
      - "3000:3000"
    networks:
      - place-network

volumes:
  postgres_data:

networks:
  place-network:
    driver: bridge

